const breakingSoundsEasy = [
    require('../../assets/sounds/breaking/easy/00waz.mp3'),
    require('../../assets/sounds/breaking/easy/01szesc.mp3'),
    require('../../assets/sounds/breaking/easy/02skarb.mp3'),
    require('../../assets/sounds/breaking/easy/03ser.mp3'),
    require('../../assets/sounds/breaking/easy/04mysz.mp3'),
    require('../../assets/sounds/breaking/easy/05mecz.mp3'),
    require('../../assets/sounds/breaking/easy/06lis.mp3'),
    require('../../assets/sounds/breaking/easy/07kosz.mp3'),
    require('../../assets/sounds/breaking/easy/08dzip.mp3'),
    require('../../assets/sounds/breaking/easy/09dzem.mp3'),
    require('../../assets/sounds/breaking/easy/10szary.mp3'),
    require('../../assets/sounds/breaking/easy/11szale.mp3'),
    require('../../assets/sounds/breaking/easy/12szafa.mp3'),
    require('../../assets/sounds/breaking/easy/13nosze.mp3'),
    require('../../assets/sounds/breaking/easy/14czapka.mp3'),
    require('../../assets/sounds/breaking/easy/15daszki.mp3'),
    require('../../assets/sounds/breaking/easy/16dzungla.mp3'),
    require('../../assets/sounds/breaking/easy/17grzebien.mp3'),
    require('../../assets/sounds/breaking/easy/18kaczor.mp3'),
    require('../../assets/sounds/breaking/easy/19kasa.mp3'),
    require('../../assets/sounds/breaking/easy/20loczki.mp3'),
    require('../../assets/sounds/breaking/easy/21losy.mp3'),
    require('../../assets/sounds/breaking/easy/22misa.mp3'),
    require('../../assets/sounds/breaking/easy/23zyrafa.mp3'),
    require('../../assets/sounds/breaking/easy/24skakanka.mp3'),
    require('../../assets/sounds/breaking/easy/25rozowy.mp3'),
    require('../../assets/sounds/breaking/easy/26naszyjnik.mp3'),
    require('../../assets/sounds/breaking/easy/27muszelka.mp3'),
    require('../../assets/sounds/breaking/easy/28maszyna.mp3')
];

export default breakingSoundsEasy;